import { createContext } from "react";
import arrowRight from "../../src/assets/images/Users/arrorwRight.svg";
import checkbox from "../../src/assets/images/Users/kvadrat.svg";
import point from "../../src/assets/images/Users/point.svg";
export const UsersContext = createContext();
export const UsersProvider = (props) => {
  console.log(props);
  const fixsed = [
    {
      id: 1,
      number: "001",
      seria: "5-112/2022",
      name: "Əliyev Əli Vəli oğlu",
      rollar: "HR manager",
      sobe: "ASAN 7 service",
      vezife: "HR assistant",
      buttons: "Active",
      img1: point,
      img2: checkbox,
      img3: arrowRight,
      type: "thing",
    },
    {
      id: 2,
      number: "001",
      seria: "5-112/2022",
      name: "Əliyev Əli Vəli oğlu",
      rollar: "HR manager",
      sobe: "ASAN 7 service",
      vezife: "HR assistant",
      buttons: "Deactive",
      img1: point,
      img2: checkbox,
      img3: arrowRight,
      type: "thing",
    },
    {
      id: 3,
      number: "001",
      seria: "5-112/2022",
      name: "Əliyev Əli Vəli oğlu",
      rollar: "HR manager",
      sobe: "ASAN 7 service",
      vezife: "HR assistant",
      buttons: "Deactive",
      img1: point,
      img2: checkbox,
      img3: arrowRight,
      type: "thing",
    },
    {
      id: 4,
      number: "001",
      seria: "5-112/2022",
      name: "Əliyev Əli Vəli oğlu",
      rollar: "HR manager",
      sobe: "ASAN 7 service",
      vezife: "HR assistant",
      buttons: "Active",
      img1: point,
      img2: checkbox,
      img3: arrowRight,
      type: "thing",
    },
    {
      id: 5,
      number: "001",
      seria: "5-112/2022",
      name: "Əliyev Əli Vəli oğlu",
      rollar: "HR manager",
      sobe: "ASAN 7 service",
      vezife: "HR assistant",
      buttons: "Active",
      img1: point,
      img2: checkbox,
      img3: arrowRight,
      type: "thing",
    },
    {
      id: 6,
      number: "001",
      seria: "5-112/2022",
      name: "Əliyev Əli Vəli oğlu",
      rollar: "HR manager",
      sobe: "ASAN 7 service",
      vezife: "HR assistant",
      buttons: "Active",
      img1: point,
      img2: checkbox,
      img3: arrowRight,
      type: "thing",
    },
    {
      id: 7,
      number: "001",
      seria: "5-112/2022",
      name: "Əliyev Əli Vəli oğlu",
      rollar: "HR manager",
      sobe: "ASAN 7 service",
      vezife: "HR assistant",
      buttons: "Active",
      img1: point,
      img2: checkbox,
      img3: arrowRight,
      type: "thing",
    },
    {
      id: 8,
      number: "001",
      seria: "5-112/2022",
      name: "Əliyev Əli Vəli oğlu",
      rollar: "HR manager",
      sobe: "ASAN 7 service",
      vezife: "HR assistant",
      buttons: "Active",
      img1: point,
      img2: checkbox,
      img3: arrowRight,
      type: "thing",
    },
    {
      id: 9,
      number: "001",
      seria: "5-112/2022",
      name: "Əliyev Əli Vəli oğlu",
      rollar: "HR manager",
      sobe: "ASAN 7 service",
      vezife: "HR assistant",
      buttons: "Active",
      img1: point,
      img2: checkbox,
      img3: arrowRight,
      type: "thing",
    },
    {
      id: 10,
      number: "001",
      seria: "5-112/2022",
      name: "Əliyev Əli Vəli oğlu",
      rollar: "HR manager",
      sobe: "ASAN 7 service",
      vezife: "HR assistant",
      buttons: "Active",
      img1: point,
      img2: checkbox,
      img3: arrowRight,
      type: "thing",
    },
    {
      id: 11,
      number: "001",
      seria: "5-112/2022",
      name: "Əliyev Əli Vəli oğlu",
      rollar: "HR manager",
      sobe: "ASAN 7 service",
      vezife: "HR assistant",
      buttons: "Active",
      img1: point,
      img2: checkbox,
      img3: arrowRight,
      type: "thing",
    },
    {
      id: 12,
      number: "001",
      seria: "5-112/2022",
      name: "Əliyev Əli Vəli oğlu",
      rollar: "HR manager",
      sobe: "ASAN 7 service",
      vezife: "HR assistant",
      buttons: "Active",
      img1: point,
      img2: checkbox,
      img3: arrowRight,
      type: "thing",
    },
  ];
  return (
    <UsersContext.Provider value={{ fixsed }}>
      {props.children}
    </UsersContext.Provider>
  );
};
